#!/bin/sh
set -eu
lab_root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
exec "$lab_root/vendor/toolchain/usr/bin/gfortran-13" \
  -B"$lab_root/vendor/toolchain/usr/lib/gcc/x86_64-linux-gnu/13/" \
  -B/usr/lib/gcc/x86_64-linux-gnu/13/ "$@"
